### ISSUE TITLE
Questions about fashion-expert-graph.pb

### ISSUE THREAD

**Issue by spyflying** [B1ueber2y/CAFD#1]
Hello! I'm interested at CAFD and would like to use it to test my model. So I'm wondering if you could share your pretrained model,  fashion-expert-graph.pb with me? Thanks for reply.

**Comment by B1ueber2y** [comment]
Hi! Thanks for your interest. You can download the model via GoogleDrive and manually assign its path in cafd.py. We have provided access to the pretrained models for mnist and fashion-mnist in the readme.

mnist
https://drive.google.com/file/d/1KAfpbl08fTuoFaUM0Wr0fcbCMoBvQSW9/view
fashion-mnist
https://drive.google.com/file/d/16SdetBp35q7C4InWiOPY9yOeq_0iMV09/view
